Style model impl
svwk/progr_eng-II pull request #5
Opened 2023-04-22 10:10 UTC by Dmitrii-Krasnov

2023-04-22 12:19 UTC, GLOBB1000 approved these changes, later dismissed

2023-04-22 17:53 UTC, svwk requested changes

2023-04-22 17:53 UTC, svwk commented on generator.py
> +    def _casual_to_formal(self, input_sentence):
Здесь нужен комментарий, непонятно для чего функция предназначена

2023-04-22 17:53 UTC, svwk commented on generator.py
> +        adequacy_scored_phrases = self.adequacy.score(input_sentence, list(gen_sentences), 0.95)
Параметр качества модели надо сделать изменяемым, для этого добавить параметр метода

2023-04-22 17:53 UTC, svwk commented on generator.py
>          """Text generation using user input
Переменную text_len переименовать и изменить ее описание

2023-04-22 17:53 UTC, svwk commented on generator.py
>                        "Length should be more than 0."
Изменить текст сообщения в соответствии с новой переменной

2023-04-22 17:53 UTC, svwk commented on generator.py
> +                    formal_text = self._casual_to_formal(sentence)
В метод self._casual_to_formal не забыть передать точность

2023-04-22 17:53 UTC, svwk commented on requirements.txt
>  uvicorn==0.21.1
Изменит условие требования на >=

2023-04-22 17:53 UTC, svwk commented on generator.py
Добавить двойные интервалы между методами

2023-05-05 06:15 UTC, GLOBB1000 approved these changes

2023-05-09 19:03 UTC, svwk approved these changes

2023-05-09 19:04 UTC, merged