Tests added
svwk/progr_eng-II pull request #8
Opened 2023-05-22 15:19 UTC by GLOBB1000

2023-05-31 15:16 UTC, svwk requested changes

2023-05-31 15:16 UTC, svwk commented on test_api.py
> +    assert req.json() != ""
Убрать мок объекты во всех тестах.

2023-05-31 15:16 UTC, svwk commented on tests/unit/test_unit.py
> +    assert a.get('Exception').startswith('Parameters are not valid')
Перенести в папку tests

2023-05-31 15:18 UTC, Dmitrii-Krasnov requested changes

2023-05-31 15:18 UTC, Dmitrii-Krasnov commented on tests/unit/test_unit.py
> +def test_generate_text_with_exception_precision_negative():
Add comments to every test

2023-06-03 06:59 UTC, svwk approved these changes

2023-06-03 07:03 UTC, Dmitrii-Krasnov approved these changes

2023-06-03 07:21 UTC, merged