Update README.md
svwk/progr_eng-II pull request #9
Opened 2023-05-22 19:23 UTC by Oshutkova

2023-05-24 16:07 UTC, svwk requested changes

2023-05-24 16:07 UTC, svwk commented on README.md
> + Модуль формолизация текста подключаемый через FastAPI
Исправить грамматическую ошибку

2023-05-24 16:07 UTC, svwk commented on README.md
> +
Исправить форматирование

2023-06-03 08:10 UTC, svwk approved these changes

2023-06-03 08:36 UTC, GLOBB1000 approved these changes

2023-06-03 08:38 UTC, merged